branches:
  only:
    - master
cache:
  bundler: true
  directories:
    - $HOME/perl5
    - $HOME/.cpanm
    - $HOME/.cpan

language: erlang
otp_release:
  - R16B03-1
install:
  - ./rebar get-deps -C rebar.config.lock
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y cpanminus perl libdbd-pg-perl build-essential
  - cpanm --local-lib=$HOME/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - cpanm --quiet --notest App::Sqitch
addons:
  postgresql: "9.3"
script:
  - export PATH=$HOME/perl5/bin:$PATH
  - sudo chmod 777 /var/run/postgresql/
  - make
  - ./rebar skip_deps=true ct
  - ./rebar skip_deps=true eunit





