driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 4
    memory: 4098
  synced_folders:
    - ['.', '/home/vagrant/opscode-omnibus']
    - ['../omnibus', '/home/vagrant/omnibus']
    - ['../omnibus-software', '/home/vagrant/omnibus-software']

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.2

platforms:
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-11.04
    run_list: apt::default
  - name: ubuntu-10.04
    run_list: apt::default
  - name: centos-5.10
  - name: centos-6.5

suites:
  - name: default
    attributes:
      omnibus:
        build_user: vagrant
        build_user_group: vagrant
        build_user_password: vagrant
        install_dir: /opt/opscode
    run_list: omnibus::default
